sudo: required
services:
  - docker


jobs:
  include:
    - stage: "Before Install"
      script: docker build -t sacheendertalwar/redis-image .

    - stage: "Run test Docker"
      script: docker run sacheendertalwar/redis-image

    - stage: "Stopping test Docker"
      script: docker stop $(docker ps -q)
