sudo: required
services:
  - docker


jobs:
  include:
    - stage: "Before Install"
      script: docker build -t sacheendertalwar/redis-image .

    - stage: "Run test Docker"
      script: docker run hello-world
